//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IceCreamProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBL_USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_USER()
        {
            this.tbl_feedback = new HashSet<tbl_feedback>();
            this.tbl_order = new HashSet<tbl_order>();
            this.tbl_recipe = new HashSet<tbl_recipe>();
        }
    
        public int u_id { get; set; }
        [Required]
        [Display(Name ="User Name")]
        public string u_name { get; set; }
        [Required]
        [Display(Name = "Email Id")]
        [ DataType(DataType.EmailAddress)]
        public string u_email { get; set; }
        [Required]
        [Display(Name = "Contact No")]
        [DataType(DataType.PhoneNumber)]

        public string u_contact { get; set; }
        [Required]
        [Display(Name = "Password")]
        [DataType(DataType.EmailAddress)]

        public string u_password { get; set; }
        [Required]
        [Display(Name = "Subscription Type")]
//        [DataType(DataType.EmailAddress)]

        public Nullable<int> u_subs { get; set; }
        [Required]
        [Display(Name = "Email Id")]
        [DataType(DataType.Password)]
        [Compare("u_password")]

        public string u_cpassword { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_feedback> tbl_feedback { get; set; }
        public virtual TBL_MEMBERSHIP TBL_MEMBERSHIP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_order> tbl_order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_recipe> tbl_recipe { get; set; }
    }
}
