//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IceCreamProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_order
    {
        public int o_id { get; set; }
        public string b_name { get; set; }
        public Nullable<int> book_id { get; set; }
        public Nullable<int> userid { get; set; }
    
        public virtual tbl_book tbl_book { get; set; }
        public virtual TBL_USER TBL_USER { get; set; }
    }
}
