//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IceCreamProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_book()
        {
            this.tbl_order = new HashSet<tbl_order>();
        }
    
        public int b_id { get; set; }
        [Required]
        [Display(Name = "Book Name")]
       
        public string b_name { get; set; }
        [Required]
        [Display(Name = "Book Description")]
        
        public string b_desc { get; set; }
        [Required]
        [Display(Name = "Book Price")]
        
        public Nullable<int> b_price { get; set; }
        [Display(Name = "Book Count")]
        public Nullable<int> b_count { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_order> tbl_order { get; set; }
    }
}
