//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IceCreamProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_order
    {
        public int o_id { get; set; }
        [Required]
        [Display(Name = "Book Name")]
        public string b_name { get; set; }
        
        [Display(Name = "Book Id")]
        public Nullable<int> book_id { get; set; }
        [Display(Name = "User Id")]
        public Nullable<int> userid { get; set; }
    
        public virtual tbl_book tbl_book { get; set; }
        public virtual TBL_USER TBL_USER { get; set; }
    }
}
